version: "3"
services:
##  tx:
#    image: danobot/rfgateway
##    container_name: tx-rf-gateway
#    restart: unless-stopped
#    volumes:
#      - ./send.py:/app/script.py
#    privileged: true
  rfgateway:
    build: .
    container_name: rfgateway
    restart: always
    volumes:
      - /home/pi/repos/rfgateway/receive-cached.py:/app/script.py
      # - /home/pi/repos/rfgateway/receive-simple.py:/app/script.py
    environment:
      - GPIO_PIN = 15
    privileged: true
