version: "3"
services:
  rfgateway:
    image: danobot/rfgateway
    container_name: rfgateway-test
    restart: unless-stopped
    volumes:
      - ./receive.py:/app/script.py
    privileged: true
  tx:
    image: danobot/rfgateway
    container_name: tx-rf-gateway
    restart: unless-stopped
    volumes:
      - ./send.py:/app/script.py
    privileged: true
